### PR TITLE
Implement collapsing margins through an entire box

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/simonsapin/victor/29)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’m not a fan of the approach in commits starting with fb75967e48baaac38768aacb7df7dfb607aab37b *Pass around a PlacementState instead of returning FlowChildren* because it breaks the abstraction boundary between layout modes. `PlacementState` is specific to placement within a block container, but now `IndependentFormattingContext::layout` requires one. The fact that `AbsolutelyPositionedFragment::layout` requires creating a dummy `PlacementState` is a sign that something is wrong.

When we add another layout mode like Flexbox for example, a flexible box will have its own logic different from `layout::flow::PlacementState` for placing its child flex item boxes and needs to call `IndependentFormattingContext::layout` for each of them.

**Comment by nox** [comment]
What if `PlacementState` passing was limited to the `layout_contents` closure passed to `layout_in_flow_non_replaced_block_level`?

**Comment by SimonSapin** [comment]
Yes, passing it around within the `flow` module is fine.

**Comment by nox** [comment]
So I guess `layout_contents` should return something like `(Vec<Fragment>, Length)` where the `Length` is the entire content block size, accounting for all uncollapsed margins in the case of an independent block formatting context. `FlowChildren` is probably a bad name for that return type though, given it's not just about flow layouts.

**Comment by nox** [comment]
I feel like our biggest problem around that code is `layout_in_flow_non_replaced_block_level` being used for both children that are in the same block formatting context and those that introduce a new independent formatting context, whereas they will have different placement code paths in the presence of floats.

**Comment by SimonSapin** [comment]
Re the name of `FlowChildren` yeah. At some point in an unmerged branch I had something equivalent named `LayoutResult`.

Re `layout_in_flow_non_replaced_block_level` behaving differently in two different cases, to what extent is it really a problem? The usual techniques should apply:

* Pass it a boolean or a two-variant enum, or
* Pass it a closure for the differing behavior (if it’s in one place), or
* Split it into two functions (or methods), with the parts in common factored out to sub-functions.

**Comment by SimonSapin** [comment]
I’ve reset this PR/branch to the *Implement collapsing margins through an entire box* commit in order to merge it, and pushed the rest to https://github.com/SimonSapin/victor/compare/margin-collapsing_.

**Pull request merged**
